### ISSUE TITLE
pull up go beyong the tab bar

### ISSUE THREAD

**Issue by AdrienDC** [arielfaur/ionic-pullup#10] opened 2016-01-07 08:34 UTC
Hi,
I have a totally random issue with is coming when I click on the footer pullup. It is expanding most of the time correctly but it happens that it may go beyond the tab menu which make me impossible to collapse it afterwards.

Anyone has experienced the same thing?

Thanks

**Comment by arielfaur** [comment] 2016-01-07 15:22
Can you maybe post your code or upload it to codepen?

**Comment by AdrienDC** [comment] 2016-01-08 08:26
I can't reproduce it on a codepen or in ionic serve, it's only happening randomly on device. I'll take a screenshot next time I got it.

**Comment by AdrienDC** [comment] 2016-01-08 08:32
![screenshot_2016-01-08-16-28-00-412](https://cloud.githubusercontent.com/assets/15973554/12193690/acc50fd8-b5ea-11e5-9277-fddb8e7ad028.jpeg)
![screenshot_2016-01-08-16-28-07-044](https://cloud.githubusercontent.com/assets/15973554/12193691/acc6e9ac-b5ea-11e5-8b64-12e369b43631.jpeg)

**Comment by arielfaur** [comment] 2016-01-16 18:13
This is strange. What Android version are you on? I have tested it on 4.1, 5.1 and 6.0 and never seen this problem. Maybe you can pay attention to what use case causes this behavior?

**Comment by AdrienDC** [comment] 2016-01-19 05:03
Yeah it's really strange, I noticed it on a real device on android 5.1.. I'll check with genymotion if I somehow experience the same.

**Comment by AdrienDC** [comment] 2016-01-23 06:52
Hello Ariel, I think I found where it's coming from. I'm using crosswalk btw.
So the issue is poping up when I go to another tab and when I come back to the first one where is located the pull up. It seems to be located in the computeDefaultHeights function when the recomputeAlHeights is triggered. If I don't recompute defaultHeights I don't see the issue again. For example the first time I had a 497px footer.height and with the issue I got 541. Without using the computeDefaultHeight, it stays at 497px.

**Comment by arielfaur** [comment] 2016-01-23 16:28
Thanks for such detailed information! I will look into it.

**Comment by pliablepixels** [comment] 2016-01-26 00:52
Yes this used to happen very often in the original version. Do you have the latest version? I believe Ariel merged changes to this - I had posted similar issues a couple of months ago and a fix was posted too.

**Comment by arielfaur** [comment] 2016-01-27 18:19
@AdrienDC I am right testing your use case on Android 4.1 with Crosswalk, and on a Nexus 7 tablet with Android 6. I am running the example project built in with the module (has tabs too). I cannot reproduce it, it seems to work just fine.
Are you sure you are using the latest version as @pliablepixels suggested? What if you try to run the example project? Do you see that behavior too?

**Comment by AdrienDC** [comment] 2016-02-02 15:48
Thanks Ariel and pliablepixel, yes I was using the last version but I'll try again on a different device

**Comment by arielfaur** [comment] 2016-02-04 10:17
@AdrienDC are you still having issues with this?

**Closed** 2016-02-25 15:08 UTC
Labels: bug
